### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by calmh** [chmduquesne/rollinghash#2]
I was going to add this to the list of used packages in the Syncthing about dialog, but noticed that the package doesn't have a license/copyright. Would you mind adding one? If you're unsure what to choose, the MIT license is friendly and common in the Go world. :)

**Comment by chmduquesne** [comment]
Yes, I'm aware of the issue.

I wanted to put it under GPLv3+, but I don't think it's compatible with
syncthing's MPLv2. I'll try to find something that does not require you to
change your license. CC0 is my next candidate.

I won't do it before tonight, though: I have a personal policy to not
commit anything from work.
