### ISSUE TITLE
Please version rollinghash

### ISSUE THREAD

**Issue by aviau** [chmduquesne/rollinghash#6]
Hello,

Could you please tag this repository?

I am the Debian Maintainer for this project and tags would help Debian keep up with new releases/bugfixes.

See:
- http://semver.org/
- http://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by aviau** [comment]
Meh. I need to go to sleep. This is tagged already.

**Comment by chmduquesne** [comment]
;-)
